# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0008_auto_20160104_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='integersetting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textsetting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
