# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0010_auto_20171104_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalintegersetting',
            name='history_type',
            field=models.CharField(choices=[('+', '\u0421\u043e\u0437\u0434\u0430\u043d'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicaltextsetting',
            name='history_type',
            field=models.CharField(choices=[('+', '\u0421\u043e\u0437\u0434\u0430\u043d'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
    ]
