# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_settings', '0011_auto_20171223_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsetting',
            name='value_en',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='textsetting',
            name='value_ru',
            field=models.TextField(default=True, null=True),
        ),
    ]
