# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0024_auto_20160125_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursioncalendar',
            name='comment_rendered',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
