# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0026_auto_20170320_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalexcursion',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexcursioncategory',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
